# Generated by Django 5.0 on 2024-01-11 23:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fastserviceorder",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="manualserviceorder",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="fastserviceorder",
            constraint=models.CheckConstraint(
                check=models.Q(("date__week_day", 7), _negated=True),
                name="core_fastserviceorder_date_not_sunday",
            ),
        ),
        migrations.AddConstraint(
            model_name="freeonlineappointment",
            constraint=models.CheckConstraint(
                check=models.Q(("date__week_day", 7), _negated=True),
                name="core_freeonlineappointment_date_not_sunday",
            ),
        ),
        migrations.AddConstraint(
            model_name="manualserviceorder",
            constraint=models.CheckConstraint(
                check=models.Q(("date__week_day", 7), _negated=True),
                name="core_manualserviceorder_date_not_sunday",
            ),
        ),
    ]
