# Generated by Django 5.0 on 2024-02-12 08:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_fastserviceorder_completed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserInformation",
            new_name="Profile",
        ),
    ]
