# Generated by Django 5.0 on 2024-02-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_profile_address_alter_profile_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fastserviceorder",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="manualserviceorder",
            name="completed",
        ),
        migrations.AddField(
            model_name="fastserviceorder",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Nedostavljen"),
                    (1, "Dostavljen"),
                    (2, "V delu"),
                    (3, "Končan"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="manualserviceorder",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Nedostavljen"),
                    (1, "Dostavljen"),
                    (2, "V delu"),
                    (3, "Končan"),
                ],
                default=0,
            ),
        ),
    ]
