# Generated by Django 5.0 on 2024-02-15 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_fastserviceorder_assigned_staff_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fastserviceorder",
            name="core_fastserviceorder_date_not_sunday",
        ),
        migrations.RemoveConstraint(
            model_name="freeonlineappointment",
            name="core_freeonlineappointment_date_not_sunday",
        ),
        migrations.RemoveConstraint(
            model_name="manualserviceorder",
            name="core_manualserviceorder_date_not_sunday",
        ),
        migrations.AddConstraint(
            model_name="fastserviceorder",
            constraint=models.CheckConstraint(
                check=models.Q(("date__week_day", 1), _negated=True),
                name="core_fastserviceorder_date_not_sunday",
            ),
        ),
        migrations.AddConstraint(
            model_name="freeonlineappointment",
            constraint=models.CheckConstraint(
                check=models.Q(("date__week_day", 1), _negated=True),
                name="core_freeonlineappointment_date_not_sunday",
            ),
        ),
        migrations.AddConstraint(
            model_name="manualserviceorder",
            constraint=models.CheckConstraint(
                check=models.Q(("date__week_day", 1), _negated=True),
                name="core_manualserviceorder_date_not_sunday",
            ),
        ),
    ]
