# Generated by Django 5.0 on 2024-02-19 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_fastserviceorder_service_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bike",
            name="is_electric",
        ),
    ]
