# Generated by Django 5.0 on 2024-02-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_bike_is_electric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fastserviceorder",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Nedostavljen"),
                    (1, "Dostavljen"),
                    (2, "V delu"),
                    (3, "Končan"),
                    (4, "Prevzet"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="manualserviceorder",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Nedostavljen"),
                    (1, "Dostavljen"),
                    (2, "V delu"),
                    (3, "Končan"),
                    (4, "Prevzet"),
                ],
                default=0,
            ),
        ),
    ]
