# Generated by Django 5.0 on 2024-02-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_fastserviceorder_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
