# Generated by Django 5.0 on 2024-02-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_bike_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="fastserviceorder",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manualserviceorder",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
