# Generated by Django 5.0 on 2024-02-22 02:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_fastserviceorderstaffcomment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fastserviceorderstaffcomment",
            old_name="date",
            new_name="date_time",
        ),
        migrations.RenameField(
            model_name="manualserviceorderstaffcomment",
            old_name="date",
            new_name="date_time",
        ),
    ]
